############################################################
# mysql database
############################################################
spring:
  datasource:
    url: jdbc:mysql://************/marine_species?useSSL=false&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: ************
    password: ************
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime=120000


############################################################
# File Transmission
############################################################
  mvc:
  servlet:
    multipart:
      max-file-size: 10MB  		# 设置单个文件最大大小为10MB
      max-request-size: 100MB  	# 设置多个文件大小为100MB


